#spring.application.name= music-service
#spring.cloud.config.uri= http://localhost:8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
fetch-registry: true
register-with-eureka: true
spring:
  application:
    name: muzix-service
  cloud:
    config:
      uri: http://localhost:8888